import type { ApiKey, Tenant } from "@prisma/client";

/**
 * Hono context variables set by middleware.
 * - requestId: UUID generated by requestIdMiddleware for every inbound request
 * - tenant / apiKey: set by apiKeyAuth for /v1/* routes
 */
export type AppVariables = {
  requestId: string;
  tenant: Tenant;
  apiKey: ApiKey & { tenant: Tenant };
  clerkWallet?: string;  // normalized 64-char wallet address from Clerk JWT
  isAdmin?: boolean;     // true when authenticated via API_SECRET_KEY
};

/**
 * Full Hono Env type. Use as:
 *   new Hono<AppEnv>()
 *   MiddlewareHandler<AppEnv>
 */
export type AppEnv = { Variables: AppVariables };
