import type { ApiKeyStatus, TenantPlan, TenantStatus } from "@prisma/client";

/**
 * The exact selected shapes `apiKeyAuth` puts on the context (KEY_SELECT) —
 * NOT the full Prisma models. Declaring the full models was a type-lie:
 * `c.set` rejected the narrower value (TS2769) and any consumer reading an
 * unselected column (e.g. createdAt) would get `undefined` at runtime.
 */
export type AuthedTenant = {
  id: string;
  name: string;
  email: string;
  plan: TenantPlan;
  status: TenantStatus;
};
export type AuthedApiKey = {
  id: string;
  status: ApiKeyStatus;
  monthlyRequestCount: number;
  monthlyResetAt: Date;
  tenant: AuthedTenant;
};

/**
 * Hono context variables set by middleware.
 * - requestId: UUID generated by requestIdMiddleware for every inbound request
 * - tenant / apiKey: set by apiKeyAuth for /v1/* routes (narrowed select)
 * - walletAddress: normalized 64-char address — set by requireClerkJwt
 * - clerkUserId: Clerk sub claim — set only on Clerk JWT path
 */
export type AppVariables = {
  requestId: string;
  tenant: AuthedTenant;
  apiKey: AuthedApiKey;
  walletAddress?: string;
  clerkUserId?: string;
  isAdmin?: boolean;
};

/**
 * Full Hono Env type. Use as:
 *   new Hono<AppEnv>()
 *   MiddlewareHandler<AppEnv>
 */
export type AppEnv = { Variables: AppVariables };
