import type { ApiKeyStatus, TenantPlan, TenantStatus, Plan, AccountStatus } from "@prisma/client";

/**
 * The exact selected shapes `apiKeyAuth` puts on the context (KEY_SELECT) —
 * NOT the full Prisma models. Declaring the full models was a type-lie:
 * `c.set` rejected the narrower value (TS2769) and any consumer reading an
 * unselected column (e.g. createdAt) would get `undefined` at runtime.
 */
export type AuthedTenant = {
  id: string;
  name: string;
  email: string;
  plan: TenantPlan;
  status: TenantStatus;
};
/**
 * The billing identity (07-identity §III) — API keys + credits are Account state.
 * Resolved from `ApiKey.accountId`; the debit target for metering.
 */
export type AuthedAccount = {
  id: string;
  plan: Plan;
  status: AccountStatus;
  creditBalance: number;
};
export type AuthedApiKey = {
  id: string;
  status: ApiKeyStatus;
  monthlyRequestCount: number;
  monthlyResetAt: Date;
  /** Legacy scoping link — null for account-native keys; removed in Phase D. */
  tenant: AuthedTenant | null;
  account: AuthedAccount;
};

/**
 * Hono context variables set by middleware.
 * - requestId: UUID generated by requestIdMiddleware for every inbound request
 * - tenant / apiKey: set by apiKeyAuth for /v1/* routes (narrowed select)
 * - walletAddress: normalized 64-char address — set by identityAuth
 * - clerkUserId: Clerk sub claim — set only on Clerk JWT path
 */
export type AppVariables = {
  requestId: string;
  /** Billing identity (07 §III) — always present on /v1/* after apiKeyAuth. */
  account: AuthedAccount;
  /** Legacy scoping (intents/claims). Present for tenant-backed keys; null-safe consumers only. Removed in Phase D. */
  tenant?: AuthedTenant;
  apiKey: AuthedApiKey;
  walletAddress?: string;
  clerkUserId?: string;
  isAdmin?: boolean;
  /** Admin wallet from adminSignatureAuth — set when the signed-request path
   *  authorizes a request (attribution/audit). Absent on the master-key path. */
  adminWallet?: string;
};

/**
 * Full Hono Env type. Use as:
 *   new Hono<AppEnv>()
 *   MiddlewareHandler<AppEnv>
 */
export type AppEnv = { Variables: AppVariables };
