-- Add the 9 ip-sponsorship intent types to IntentType enum
-- ALTER TYPE ... ADD VALUE cannot run inside a transaction block in PostgreSQL
ALTER TYPE "IntentType" ADD VALUE IF NOT EXISTS 'CREATE_SPONSORSHIP_OFFER';
ALTER TYPE "IntentType" ADD VALUE IF NOT EXISTS 'SET_SPONSORSHIP_OFFER_OPEN';
ALTER TYPE "IntentType" ADD VALUE IF NOT EXISTS 'PLACE_SPONSORSHIP_BID';
ALTER TYPE "IntentType" ADD VALUE IF NOT EXISTS 'RETRACT_SPONSORSHIP_BID';
ALTER TYPE "IntentType" ADD VALUE IF NOT EXISTS 'ACCEPT_SPONSORSHIP_BID';
ALTER TYPE "IntentType" ADD VALUE IF NOT EXISTS 'CREATE_SPONSORSHIP_PROPOSAL';
ALTER TYPE "IntentType" ADD VALUE IF NOT EXISTS 'WITHDRAW_SPONSORSHIP_PROPOSAL';
ALTER TYPE "IntentType" ADD VALUE IF NOT EXISTS 'ACCEPT_SPONSORSHIP_PROPOSAL';
ALTER TYPE "IntentType" ADD VALUE IF NOT EXISTS 'REJECT_SPONSORSHIP_PROPOSAL';
